name: ppsg
channels:
  - conda-forge
  - usgs-astrogeology
dependencies:
 - python >=3.7
 - pyqt
 - numpy
 - pandas
 - scipy
 - matplotlib
 - scikit-learn
 - docutils
 - plio>=1.3
 - networkx>=2.5
 - pyhat
 - pip
 - pip:
   - pysptools
