# -*- coding: utf-8 -*-

# Automatically generated - don't edit.
# Use `python setup.py build_ui` to update it.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formGroupBox = QtWidgets.QGroupBox(Form)
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.numOfIterationsLabel = QtWidgets.QLabel(self.formGroupBox)
        self.numOfIterationsLabel.setObjectName("numOfIterationsLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.numOfIterationsLabel)
        self.numOfIterationsLineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.numOfIterationsLineEdit.setProperty("maximum", 999999999)
        self.numOfIterationsLineEdit.setProperty("value", 300)
        self.numOfIterationsLineEdit.setObjectName("numOfIterationsLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.numOfIterationsLineEdit)
        self.toleranceLabel = QtWidgets.QLabel(self.formGroupBox)
        self.toleranceLabel.setObjectName("toleranceLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.toleranceLabel)
        self.toleranceLineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.toleranceLineEdit.setProperty("decimals", 5)
        self.toleranceLineEdit.setProperty("singleStep", 0.001)
        self.toleranceLineEdit.setProperty("value", 0.001)
        self.toleranceLineEdit.setObjectName("toleranceLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.toleranceLineEdit)
        self.alpha_label = QtWidgets.QLabel(self.formGroupBox)
        self.alpha_label.setObjectName("alpha_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.alpha_label)
        self.alpha_lineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.alpha_lineEdit.setObjectName("alpha_lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.alpha_lineEdit)
        self.alpha1Label = QtWidgets.QLabel(self.formGroupBox)
        self.alpha1Label.setObjectName("alpha1Label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.alpha1Label)
        self.alpha1LineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.alpha1LineEdit.setProperty("decimals", 5)
        self.alpha1LineEdit.setProperty("singleStep", 0.001)
        self.alpha1LineEdit.setProperty("value", 0.001)
        self.alpha1LineEdit.setObjectName("alpha1LineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.alpha1LineEdit)
        self.alpha2Label = QtWidgets.QLabel(self.formGroupBox)
        self.alpha2Label.setObjectName("alpha2Label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.alpha2Label)
        self.alpha2LineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.alpha2LineEdit.setProperty("decimals", 8)
        self.alpha2LineEdit.setProperty("singleStep", 1e-06)
        self.alpha2LineEdit.setProperty("value", 1e-06)
        self.alpha2LineEdit.setObjectName("alpha2LineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.alpha2LineEdit)
        self.lambda_label = QtWidgets.QLabel(self.formGroupBox)
        self.lambda_label.setObjectName("lambda_label")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lambda_label)
        self.lambda_lineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.lambda_lineEdit.setObjectName("lambda_lineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lambda_lineEdit)
        self.lambda1Label = QtWidgets.QLabel(self.formGroupBox)
        self.lambda1Label.setObjectName("lambda1Label")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.lambda1Label)
        self.lambda1LineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.lambda1LineEdit.setProperty("decimals", 8)
        self.lambda1LineEdit.setProperty("singleStep", 1e-06)
        self.lambda1LineEdit.setProperty("value", 1e-06)
        self.lambda1LineEdit.setObjectName("lambda1LineEdit")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lambda1LineEdit)
        self.lambda2_label = QtWidgets.QLabel(self.formGroupBox)
        self.lambda2_label.setObjectName("lambda2_label")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.lambda2_label)
        self.lambda2LineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.lambda2LineEdit.setObjectName("lambda2LineEdit")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.lambda2LineEdit)
        self.fitInterceptLabel = QtWidgets.QLabel(self.formGroupBox)
        self.fitInterceptLabel.setObjectName("fitInterceptLabel")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.fitInterceptLabel)
        self.fitIntercept_List = QtWidgets.QListWidget(self.formGroupBox)
        self.fitIntercept_List.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.fitIntercept_List.setObjectName("fitIntercept_List")
        item = QtWidgets.QListWidgetItem()
        self.fitIntercept_List.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.fitIntercept_List.addItem(item)
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.fitIntercept_List)
        self.normalizeLabel = QtWidgets.QLabel(self.formGroupBox)
        self.normalizeLabel.setObjectName("normalizeLabel")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.normalizeLabel)
        self.normalize_List = QtWidgets.QListWidget(self.formGroupBox)
        self.normalize_List.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.normalize_List.setObjectName("normalize_List")
        item = QtWidgets.QListWidgetItem()
        self.normalize_List.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.normalize_List.addItem(item)
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.normalize_List)
        self.alpha_checkbox = QtWidgets.QCheckBox(self.formGroupBox)
        self.alpha_checkbox.setChecked(True)
        self.alpha_checkbox.setObjectName("alpha_checkbox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.alpha_checkbox)
        self.lambda_checkbox = QtWidgets.QCheckBox(self.formGroupBox)
        self.lambda_checkbox.setChecked(True)
        self.lambda_checkbox.setObjectName("lambda_checkbox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lambda_checkbox)
        self.verticalLayout.addWidget(self.formGroupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(("Form"))
        self.numOfIterationsLabel.setText(("# of iterations"))
        self.numOfIterationsLineEdit.setText(("300"))
        self.toleranceLabel.setText(("Tolerance"))
        self.toleranceLineEdit.setText(("0.001"))
        self.alpha_label.setText(("Initial Alpha"))
        self.alpha_lineEdit.setText(("1"))
        self.alpha1Label.setText(("Alpha 1"))
        self.alpha1LineEdit.setText(("0.000001"))
        self.alpha2Label.setText(("Alpha 2"))
        self.alpha2LineEdit.setText(("0.000001"))
        self.lambda_label.setText(("Initial Lambda"))
        self.lambda_lineEdit.setText(("1"))
        self.lambda1Label.setText(("Lambda 1"))
        self.lambda1LineEdit.setText(("0.000001"))
        self.lambda2_label.setText(("Lambda 2"))
        self.lambda2LineEdit.setText(("0.000001"))
        self.fitInterceptLabel.setText(("Fit Intercept"))
        __sortingEnabled = self.fitIntercept_List.isSortingEnabled()
        self.fitIntercept_List.setSortingEnabled(False)
        item = self.fitIntercept_List.item(0)
        item.setText(("True"))
        item = self.fitIntercept_List.item(1)
        item.setText(("False"))
        self.fitIntercept_List.setSortingEnabled(__sortingEnabled)
        self.normalizeLabel.setText(("Normalize"))
        __sortingEnabled = self.normalize_List.isSortingEnabled()
        self.normalize_List.setSortingEnabled(False)
        item = self.normalize_List.item(0)
        item.setText(("True"))
        item = self.normalize_List.item(1)
        item.setText(("False"))
        self.normalize_List.setSortingEnabled(__sortingEnabled)
        self.alpha_checkbox.setText(("Use default Alpha"))
        self.lambda_checkbox.setText(("Use default Lambda"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

